### ISSUE TITLE
不能翻译多行文本

### ISSUE THREAD

**Issue by TaylorBoy** [jtaox/vscode-extension-translatorX#2]
选中多行文本时, 只翻译了第一行:

原文: 
`
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
`

结果: 
`
'The module 'vscode' contains the VS Code extensibility API // Import the module and reference it with the alias vscode in your code below'翻译结果:

模块“vs code”包含vs代码扩展性API
`

**Comment by jtaox** [comment]
这个问题和目前使用的api有关系，后面版本会加入youdao等api

**Comment by TaylorBoy** [comment]
> 这个问题和目前使用的api有关系，后面版本会加入youdao等api

这个我用百度的API('http://api.fanyi.baidu.com/api/trans/vip/translate')可以翻译过来, 就是有200万字符限制, 然后这个API查询单词只有一个释义, 用来翻译长句还是可以的.  

你所用的 API 我没用过不了解, 如果可以提供可配置 API 的就更好啦哈!

**Comment by jtaox** [comment]
> > 这个问题和目前使用的api有关系，后面版本会加入youdao等api
> 
> 这个我用百度的API('[http://api.fanyi.baidu.com/api/trans/vip/translate')可以翻译过来](http://api.fanyi.baidu.com/api/trans/vip/translate')%E5%8F%AF%E4%BB%A5%E7%BF%BB%E8%AF%91%E8%BF%87%E6%9D%A5), 就是有200万字符限制, 然后这个API查询单词只有一个释义, 用来翻译长句还是可以的.
> 
> 你所用的 API 我没用过不了解, 如果可以提供可配置 API 的就更好啦哈!

已经集成了有道api，可以满足需求。另外还想加朗读功能，不过播放这块遇到很多问题😶
