### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by cmdbug** [jtaox/vscode-extension-translatorX#3]
增加鼠标右键选中文本翻译。而不是开启翻译功能鼠标一移上去就立即翻译。这个跟鼠标移上去默认显示方法定义，变量类型等一起显示有点乱。

**Comment by jtaox** [comment]
可以添加这种方式，不过我没找到单独展示hover的api，所以翻译结果可能得放到比如Status Bar或其他什么地方了
