### ISSUE TITLE
你好,你这个插件是否支持快速翻译替换?

### ISSUE THREAD

**Issue by qiacoucc** [jtaox/vscode-extension-translatorX#4]
你好,你这个插件是否支持快速翻译替换?
就是把翻译结果替换选中的字符 ,官方是有相关的api的

**Comment by jtaox** [comment]
目前还不支持，不过可以在下次更新的时候加入这个功能。

**Comment by qiacoucc** [comment]
嗯嗯 期待加入 感谢
 
------------------ Original ------------------
